name: pdp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - fastcore
  - matplotlib
  - jupyter
  - ipykernel
  - ruff
  - pre-commit
  - pytest
  - pip
  - pip:
    - aiofiles
    - httpx
    - psycopg2-binary
    - asyncpg
    - sqlalchemy[asyncio]  # Includes greenlet for async operations
    - sqlmodel
    - python-dotenv
